# Music Industry

In [1]:
import pandas as pd
wikiurl = 'https://en.wikipedia.org/wiki/Music_industry'
tables = pd.read_html(wikiurl)

### Album Sales and Market Value in the World in 2014.

In [9]:
albums_sales_2014_df = tables[2] #Music markets, with total retail value, and share of Physical, Digital records, 2014
albums_sales_2014_df

,Ranking,Market,Retail value US $ (millions),% Change,Physical,Digital,Performance rights,Synchronization
0,1,United States,4898.3,2.1%,26%,71%,0%,4%
1,2,Japan,2627.9,−5.5%,78%,17%,3%,1%
2,3,Germany,1404.8,1.9%,70%,22%,7%,1%
3,4,United Kingdom,1334.6,−2.8%,41%,45%,12%,2%
4,5,France,842.8,−3.4%,57%,27%,13%,3%
5,6,Australia,376.1,−6.8%,32%,56%,9%,2%
6,7,Canada,342.5,−11.3%,38%,53%,6%,2%
7,8,South Korea,265.8,19.2%,38%,58%,3%,1%
8,9,Brazil,246.5,2.0%,41%,37%,21%,1%
9,10,Italy,235.2,4.1%,51%,33%,13%,3%
10,11,Netherlands,204.8,2.1%,45%,38%,16,1%
11,12,Sweden,189.4,1.3%,15%,73%,10%,2%
12,13,Spain,181.1,15.2%,47%,35%,17%,1%
13,14,Mexico,130.3,−1.4%,41%,53%,4%,2%
14,15,Norway,119.9,0.1%,14%,72%,12%,2%
15,16,Austria,114.9,−2.7%,65%,22%,13%,1%
16,17,Belgium,111.2,−5.8%,49%,28%,22%,0%
17,18,Switzerland,108.2,−8.1%,52%,38%,9%,0%
18,19,China,105.2,5.6%,12%,87%,0%,1%
19,20,India,100.2,−10.1%,31%,58%,8%,3%

### Total Revenue by Year

In [12]:
revenue_yr_df = tables[4].drop(columns='Notes') #Global trade revenue according to the IFPI.
revenue_yr_df

    Year         Revenue  Change
0   2005   $20.7 billion     −3%
1   2006   $19.6 billion     −5%
2   2007   $18.8 billion     −4%
3   2008   $18.4 billion     −2%
4   2009   $17.4 billion     −5%
5   2010   $16.8 billion   −3.4%
6   2011   $16.2 billion     −4%
7   2012   $16.5 billion     +2%
8   2013     $15 billion     −9%
9   2014  $14.97 billion   −0.2%
10  2015     $15 billion   +3.2%
11  2016   $15.7 billion     +5%
12  2017   $17.4 billion  +10.8%
13  2018   $19.1 billion   +9.7%
14  2019   $20.2 billion   +8.2%
15  2020   $21.6 billion   +7.4%
16  2021   $25.9 billion  +18.5%
17  2022   $26.2 billion     +9%